<div id="myModal" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: none;">
	<div class="span4" style="display: none;">
		<div class="row-fluid span4">
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption"><i class="icon-reorder"></i>Validation States</div>
					<div class="tools">
						<a href="javascript:;" class="remove"></a>
					</div>
				</div>
				<div class="portlet-body form">
					<!-- BEGIN FORM-->
					<form action="#" class="form-horizontal">
						<div class="control-group">
							<label class="control-label">archive计算公式<span class="required">*</span></label>
							<div class="controls">
								<input type="text" class="span11 m-wrap"  name="cf_type">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">数据正确性阀值<span class="required">*</span></label>
							<div class="controls">
								<input type="text" class="span11 m-wrap"  name="xff">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">合并时间点个数<span class="required">*</span></label>
							<div class="controls">
								<input type="text" class="span11 m-wrap" name="step">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">合并最终总条数<span class="required">*</span></label>
							<div class="controls">
								<input type="text" class="span11 m-wrap"  name="rows">
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">描述信息<span class="required">*</span></label>
							<div class="controls">
								<input type="text" class="span11 m-wrap" name="title">
							</div>
						</div>
						<!--
						<div class="control-group warning">
							<label class="control-label">Input with warning</label>
							<div class="controls input-icon">
								<input type="text" class="span10 m-wrap">
								<span class="input-warning tooltips" data-original-title="please write a valid email">
								<i class="icon-warning-sign"></i>
								</span>
							</div>
						</div>
						<div class="control-group error">
							<label class="control-label">Input with error</label>
							<div class="controls input-icon">
								<input type="text" class="span10 m-wrap">
								<span class="input-error tooltips" data-original-title="please write a valid email">
								<i class="icon-exclamation-sign"></i>
								</span>
							</div>
						</div>
						<div class="control-group success">
							<label class="control-label">Input with success</label>
							<div class="controls input-icon">
								<input type="text" class="span10 m-wrap">
								<span class="input-success tooltips" data-original-title="Success input!">
								<i class="icon-ok"></i>
								</span>
							</div>
						</div>
						-->
						<div class="form-actions">
							<button type="submit" class="btn blue">Save</button>
							<button type="button" class="btn">Cancel</button>
						</div>
					</form>
					<!-- END FORM-->
				</div>
			</div>
		</div>
	</div>
	<div style="float: right;" class="span5">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption"><i class="icon-cogs"></i>监控器Archive管理</div>
				<div class="tools">
					<button class="btn gray" id="sample_editable_1_new">
						Add New <i class="icon-plus"></i>																				 </button>
					<!--<a href="javascript:;" class="collapse"></a>
					<a href="#portlet-config" data-toggle="modal" class="config"></a>
					<a href="javascript:;" class="reload"></a>
					<a href="javascript:;" class="remove"></a>
					-->
				</div>
			</div>
		</div>
		<div class="portlet-body">
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>#</th>
						<th>title</th>
						<th>xff</th>
						<th>rows</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody id="attr_list"></tbody>
			</table>
		</div>
		<div class="modal-footer">
		  <button class="btn" data-dismiss="modal">关闭</button>
		  <button class="btn btn-primary">Save changes</button>
		</div>
		</div>
		</div>
	</div>
</div>
<!-- END DELAY -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<script src="js/index.js" type="text/javascript"></script>
<script src="js/swan.js" type="text/javascript"></script>
<script src="js/monitor.js" type="text/javascript"></script>
<!-- END JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<div class="row-fluid">
	<div class="span12">
		<!-- BEGIN STYLE CUSTOMIZER -->
		<div class="color-panel hidden-phone">
			<div class="color-mode-icons icon-color"></div>
			<div class="color-mode-icons icon-color-close"></div>
			<div class="color-mode">
				<p>THEME COLOR</p>
				<ul class="inline">
					<li class="color-black current color-default" data-style="default"></li>
					<li class="color-blue" data-style="blue"></li>
					<li class="color-brown" data-style="brown"></li>
					<li class="color-purple" data-style="purple"></li>
					<li class="color-grey" data-style="grey"></li>
					<li class="color-white color-light" data-style="light"></li>
				</ul>
				<label>
					<span>Layout</span>
					<select class="layout-option m-wrap small">
						<option value="fluid" selected>Fluid</option>
						<option value="boxed">Boxed</option>
					</select>
				</label>
				<label>
					<span>Header</span>
					<select class="header-option m-wrap small">
						<option value="fixed" selected>Fixed</option>
						<option value="default">Default</option>
					</select>
				</label>
				<label>
					<span>Sidebar</span>
					<select class="sidebar-option m-wrap small">
						<option value="fixed">Fixed</option>
						<option value="default" selected>Default</option>
					</select>
				</label>
				<label>
					<span>Footer</span>
					<select class="footer-option m-wrap small">
						<option value="fixed">Fixed</option>
						<option value="default" selected>Default</option>
					</select>
				</label>
			</div>
		</div>
		<!-- END BEGIN STYLE CUSTOMIZER -->
		<!-- BEGIN PAGE TITLE & BREADCRUMB-->
		<h3 class="page-title">
			Editable Tables <small>editable table samples</small>
		</h3>
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="index.html">Home</a>
				<i class="icon-angle-right"></i>
			</li>
			<li>
				<a href="#">Data Tables</a>
				<i class="icon-angle-right"></i>
			</li>
			<li><a href="#">Editable Tables</a></li>
		</ul>
		<!-- END PAGE TITLE & BREADCRUMB-->
	</div>
</div>
<!-- END PAGE HEADER-->
