<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="index.html">Home</a>
				<span class="icon-angle-right"></span>
			</li>
			<li>
				<a href="#">Form Stuff</a>
				<span class="icon-angle-right"></span>
			</li>
			<li><a href="#">Form Layouts</a></li>
		</ul>
	</div>
</div>
<!-- BEGIN PAGE CONTAINER-->
<div class="container-fluid">
	<!-- BEGIN PAGE CONTENT-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet box blue tabbable">
				<div class="portlet-title">
					<div class="caption">
						<i class="icon-reorder"></i>
						<span class="hidden-480">General Layouts</span>
					</div>
				</div>
				<div class="portlet-body form">
					<div class="tabbable portlet-tabs">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#portlet_tab1" data-toggle="tab">Default</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="portlet_tab1">
								<!-- BEGIN FORM-->
								<form action="/device_doAdd" method="post" class="form-horizontal" id="deviceForm">
									<div class="control-group">
										<label class="control-label">设备名称</label>
										<div class="controls">
											<input type="text" name="device_name" placeholder="device name" class="m-wrap medium" />
											<span class="help-inline">*</span>
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">设备IP</label>
										<div class="controls">
											<input type="text" placeholder="device IP" name="host_name" class="m-wrap medium" />
											<span class="help-inline">*</span>
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">设备信息</label>
										<div class="controls">
											<textarea class="large m-wrap" name="display_name" rows="3"></textarea>
										</div>
									</div>
									<div class="form-actions">
										<button type="button" class="btn blue" id="deviceBtn"><i class="icon-ok"></i> Save</button>
										<button type="button" class="btn">Cancel</button>
									</div>
								</form>
								<!-- END FORM-->
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- END SAMPLE FORM PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT-->
</div>
<!-- END PAGE CONTAINER-->
<script src="js/device.js" type="text/javascript"></script>
<script type="text/javascript">
	var swanDevice = new SwanDevice();
	swanDevice.setThisName('swanDevice');
	swanDevice.init();
</script>
