<link rel="stylesheet" type="text/css" href="media/css/select2_metro.css" />
<link rel="stylesheet" href="media/css/DT_bootstrap.css" />
<link rel="shortcut icon" href="media/image/favicon.ico" />
<link rel="stylesheet" href="media/css/DT_bootstrap.css" />
<script src="media/js/jquery.dataTables.js" type="text/javascript"></script>
<script src="media/js/DT_bootstrap.js" type="text/javascript"></script>
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="index.html">Home</a>
				<i class="icon-angle-right"></i>
			</li>
			<li>
				<a href="#">Data Tables</a>
				<i class="icon-angle-right"></i>
			</li>
			<li><a href="#">Editable Tables</a></li>
		</ul>
	</div>
</div>
<!-- END PAGE TITLE & BREADCRUMB-->
<!-- BEGIN PAGE CONTAINER-->
<div class="container-fluid">
	<!-- BEGIN PAGE CONTENT-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE PORTLET-->
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption"><i class="icon-edit"></i>Editable Table</div>
					<div class="tools">
						<a href="javascript:;" class="collapse"></a>
						<a href="#portlet-config" data-toggle="modal" class="config"></a>
						<a href="javascript:;" class="reload"></a>
						<a href="javascript:;" class="remove"></a>
					</div>
				</div>
				<div class="portlet-body">
					<div class="clearfix">
						<div class="btn-group">
							<button id="sample_editable_1_new" class="btn green">
							Add New <i class="icon-plus"></i>
							</button>
						</div>
						<div class="btn-group pull-right">
							<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
							</button>
							<ul class="dropdown-menu pull-right">
								<li><a href="#">Print</a></li>
								<li><a href="#">Save as PDF</a></li>
								<li><a href="#">Export to Excel</a></li>
							</ul>
						</div>
					</div>
					<table class="table table-striped table-hover table-bordered" id="device_table">
						<thead>
							<tr>
								<th>#</th>
								<th>设备名称</th>
                                <th>设备IP</th>
							 	<th>设备信息</th>
								<th>Edit</th>
								<th>Delete</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTAINER-->
<!-- END CONTAINER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<script src="js/device.js"></script>
<!-- END JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<script>
	var device = new SwanDevice();
	device.setThisName('device');
	device.init();
</script>
