<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="/">SWANSOFT Home</a>
				<span class="icon-angle-right"></span>
			</li>
			<li>
				<a href="javascript:;"><%= className %></a>
				<span class="icon-angle-right"></span>
			</li>
			<li><a href="javascript:;"><%= subClassName %></a></li>
		</ul>
	</div>
</div>
<!-- BEGIN PAGE CONTAINER-->
<div class="container-fluid">
	<!-- BEGIN PAGE CONTENT-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption">
						<i class="icon-reorder"></i>
						<span class="hidden-480"><%= subClassName %></span>
					</div>
				</div>
				<div class="portlet-body form">
					<!-- BEGIN FORM-->
					<form action="/device_doAdd" method="post" class="form-horizontal" id="deviceForm">
						<div class="control-group">
							<label class="control-label">设备名称<span class="required">*</span></label>
							<div class="controls">
								<input type="text" name="device_name" placeholder="device name" class="m-wrap span6" />
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">设备IP<span class="required">*</span></label>
							<div class="controls">
								<input type="text" placeholder="device IP" name="host_name" class="m-wrap span6" />
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">心跳线超时时间<span class="required">*</span></label>
							<div class="controls">
								<input type="text" placeholder="20" name="heartbeat_time" class="m-wrap span6" />
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">设备信息<span class="required">&nbsp;&nbsp;</span></label>
							<div class="controls">
								<textarea class="span6 m-wrap" name="display_name" rows="3"></textarea>
							</div>
						</div>
						<div class="form-actions">
							<button type="button" class="btn blue" id="deviceBtn"><i class="icon-ok"></i> Save</button>
							<button type="button" class="btn">Cancel</button>
						</div>
					</form>
					<!-- END FORM-->
				</div>
			</div>
			<!-- END SAMPLE FORM PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT-->
</div>
<!-- END PAGE CONTAINER-->
<script src="media/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="js/device.js" type="text/javascript"></script>
<script type="text/javascript">
	var swanDevice = new SwanDevice();
	swanDevice.init();
	swanDevice.initAdd();
</script>
