<link rel="stylesheet" type="text/css" href="media/css/select2_metro.css" />
<link rel="stylesheet" type="text/css" href="media/css/DT_bootstrap.css" />
<link rel="stylesheet" type="text/css" href="media/css/uniform.default.css" />
<link rel="shortcut icon" href="media/image/favicon.ico" />
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="/">SWANSOFT Home</a>
				<i class="icon-angle-right"></i>
			</li>
			<li>
				<a href="#"><%= className %></a>
				<i class="icon-angle-right"></i>
			</li>
			<li><a href="#"><%= subClassName %></a></li>
		</ul>
	</div>
</div>
<!-- END PAGE TITLE & BREADCRUMB-->
<!-- BEGIN PAGE CONTAINER-->
<div class="container-fluid">
	<!-- BEGIN PAGE CONTENT-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE PORTLET-->
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption"><i class="icon-edit"></i><%= subClassName %></div>
					<div class="tools">
						<a href="javascript:;" class="reload"></a>
					</div>
				</div>
				<div class="portlet-body">
					<table class="table table-striped table-hover table-bordered" id="device_table">
						<thead>
							<tr>
								<th style="width:8px;"><div class="checker"><span class=""><input type="checkbox" class="group-checkable" data-set="#device_table .checkboxes" /></span></div></th>
								<th>设备名称</th>
                                <th>设备IP</th>
							 	<th>设备信息</th>
								<th>Edit</th>
								<th>Delete</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTAINER-->
<!-- END CONTAINER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->

<script src="media/js/jquery.dataTables.js" type="text/javascript"></script>
<script src="media/js/DT_bootstrap.js" type="text/javascript"></script>
<script src="js/device.js"></script>
<!-- END JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<script>
	var device = new SwanDevice();
	device.setThisName('device');
	device.init();
	device.loadIndex();
</script>
