<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="media/css/select2_metro.css" />
<link rel="stylesheet" href="media/css/DT_bootstrap.css" />
<script src="media/js/jquery.dataTables.js" type="text/javascript"></script>
<script src="media/js/DT_bootstrap.js" type="text/javascript"></script>
<div class="row-fluid">
	<div class="span12">
		<!-- BEGIN PAGE TITLE & BREADCRUMB-->
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="index.html">Home</a>
				<i class="icon-angle-right"></i>
			</li>
			<li>
				<a href="#">Data Tables</a>
				<i class="icon-angle-right"></i>
			</li>
			<li><a href="#">Editable Tables</a></li>
		</ul>
		<!-- END PAGE TITLE & BREADCRUMB-->
	</div>
</div>
<!-- BEGIN PAGE CONTENT-->
<div class="row-fluid">
	<div class="span12">
		<!-- BEGIN EXAMPLE TABLE PORTLET-->
		<div class="portlet box blue">
			<div class="portlet-body">
				<div class="clearfix">
					<div class="btn-group">
						<button id="sample_editable_1_new" class="btn green">
						Add New <i class="icon-plus"></i>
						</button>
					</div>
					<div class="btn-group pull-right">
						<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
						</button>
						<ul class="dropdown-menu pull-right">
							<li><a href="#">Print</a></li>
							<li><a href="#">Save as PDF</a></li>
							<li><a href="#">Export to Excel</a></li>
						</ul>
					</div>
				</div>
				<table class="table table-striped table-hover table-bordered" id="madapter_list">
					<thead>
						<tr>
							<th>#</th>
							<th>监控器名称</th>
							<th>STEPS</th>
							<th>描述</th>
							<th id="table-center-15">监控详情</th>
							<th id="table-center-10">操作</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
		<!-- END EXAMPLE TABLE PORTLET-->
	</div>
</div>
<script src="js/madapter.js" type="text/javascript"></script>
<script>
	var mAdapter = new SwanMAdapter();
	mAdapter.setThisName('mAdapter');
	mAdapter.init();
	mAdapter.loadIndexList();
</script>
