<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="media/css/select2_metro.css" />
<link rel="stylesheet" href="media/css/DT_bootstrap.css" />
<script src="media/js/jquery.dataTables.js" type="text/javascript"></script>
<script src="media/js/DT_bootstrap.js" type="text/javascript"></script>
<div class="row-fluid">
	<div class="span12">
		<!-- BEGIN PAGE TITLE & BREADCRUMB-->
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="/">Home</a>
				<i class="icon-angle-right"></i>
			</li>
			<li>
				<a href="javascript:;"><%= className %></a>
				<i class="icon-angle-right"></i>
			</li>
			<li><a href="javascript:;"><%= subClassName %></a></li>
		</ul>
		<!-- END PAGE TITLE & BREADCRUMB-->
	</div>
</div>
<!-- BEGIN PAGE CONTENT-->
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE PORTLET-->
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption"><i class="icon-edit"></i><%= subClassName %></div>
					<div class="tools">
						<a href="javascript:;" class="reload"></a>
					</div>
				</div>
				<div class="portlet-body">
					<table class="table table-striped table-hover table-bordered" id="madapter_list">
						<thead>
							<tr>
								<th style="width: 8px;">
									<div class="checker">
										<span><input type="checkbox" class="group-checkable" data-set="#madapter_list .checkboxes" /></span>
									</div>
								</th>
								<th>监控器名称</th>
								<th>STEPS</th>
								<th>描述</th>
								<th id="table-center-15">监控详情</th>
								<th id="table-center-10">操作</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>
	</div>
</div>
<script src="js/madapter.js" type="text/javascript"></script>
<script>
	var mAdapter = new SwanMAdapter();
	mAdapter.setThisName('mAdapter');
	mAdapter.init();
	mAdapter.loadIndexList();
</script>
