<link rel="stylesheet" type="text/css" href="media/css/select2_metro.css" />
<link rel="stylesheet" href="media/css/DT_bootstrap.css" />
<link rel="shortcut icon" href="media/image/favicon.ico" />
<link rel="stylesheet" href="media/css/DT_bootstrap.css" />
<script src="media/js/DT_bootstrap.js" type="text/javascript"></script>
<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="/">Home</a>
				<i class="icon-angle-right"></i>
			</li>
			<li>
				<a href="#"><%= className %></a>
				<i class="icon-angle-right"></i>
			</li>
			<li><a href="#"><%= subClassName %></a></li>
		</ul>
	</div>
</div>
<!-- END PAGE TITLE & BREADCRUMB-->
<!-- BEGIN PAGE CONTAINER-->
<div class="container-fluid">
	<!-- BEGIN PAGE CONTENT-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE PORTLET-->
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption"><i class="icon-edit"></i><%= subClassName %></div>
					<div class="tools">
						<a href="javascript:;" class="reload"></a>
					</div>
				</div>
				<div class="portlet-body">
					<table class="table table-striped table-hover table-bordered" id="madapterAttr_table" madapter_id="<%= madapter_id %>">
						<thead>
							<tr>
								<th style="width:8px;"><div class="checker"><span class=""><input type="checkbox" class="group-checkable" data-set="#madapterAttr_table .checkboxes" /></span></div></th>
								<th>属性名称</th>
                                <th>显示名称</th>
							 	<th>表单类型</th>
							 	<th>表单数据</th>
							 	<th>默认值</th>
								<th style="width: 150px;">操作</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTAINER-->
<!-- END CONTAINER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<script src="js/mAdapterAttr.js" type="text/javascript"></script>
<!-- END JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<script type="text/javascript">
	var mAdapterAttr = new SwanmAdapterAttr();

	mAdapterAttr.setThisName('device');
	mAdapterAttr.init();
	mAdapterAttr.loadIndexList();
</script>
