<link href="media/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<!-- BEGIN PAGE CONTAINER-->
<!-- BEGIN PAGE HEADER-->
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="/">SWANSOFT Home</a>
				<span class="icon-angle-right"></span>
			</li>
			<li>
				<a href="javascript:;"><%= className %></a>
				<span class="icon-angle-right"></span>
			</li>
			<li><a href="javascript:;"><%= subClassName %></a></li>
		</ul>
	</div>
</div>
<!-- END PAGE HEADER-->
<div class="container-fluid">
	<!-- BEGIN PAGE CONTENT-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption">
						<i class="icon-reorder"></i>
						<span class="hidden-480"><%= subClassName %></span>
					</div>
				</div>
				<div class="portlet-body form">
					<!-- BEGIN FORM-->
					<form action="#" method="post" class="form-horizontal" id="mAdapterForm">
						<div class="control-group">
							<label class="control-label">名称<span class="required">*</span></label>
							<div class="controls">
								<input type="text" name="name" placeholder="mAdapter name" class="m-wrap span6" />
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">STEPS<span class="required">*</span></label>
							<div class="controls">
								<input type="text" placeholder="300" name="steps" class="m-wrap span6" />
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">store_type<span class="required">*</span></label>
							<div class="controls">
								<label class="checkbox line">
								<input type="checkbox" name="store_type[]" value="2" /> RRD
								</label>
								<label class="checkbox line">
								<input type="checkbox" name="store_type[]" value="4" /> REDIS
								</label>
								<span class="help-block">(select at least one)</span>
								<div id="store_type_error"></div>	
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">madapter_type<span class="required">*</span></label>
							<div class="controls">
								<label class="radio line">
								<input type="radio" name="madapter_type" value="1"/>
								core类型
								</label>
								<label class="radio line">
								<input type="radio" name="madapter_type" value="2"/>
								normal类型
								</label>
								<div id="madapter_type_error"></div>	
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">描述</label>
							<div class="controls">
								<textarea class="span6 m-wrap" name="display_name" rows="3"></textarea>
							</div>
						</div>
						<div class="form-actions">
							<button type="button" class="btn blue" id="mAdapter_btn"><i class="icon-ok"></i> Save</button>
							<button type="button" class="btn">Cancel</button>
						</div>
					</form>
					<!-- END FORM-->
				</div>
			</div>
			<!-- END SAMPLE FORM PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT-->
</div>
<!-- END PAGE CONTAINER-->

<script src="media/js/jquery.uniform.min.js" type="text/javascript"></script>
<script src="media/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="js/madapter.js" type="text/javascript"></script>

<script type="text/javascript">
	jQuery(document).ready(function() {
		var mAdapter = new SwanmAdapter();
		mAdapter.handleUniform();
		mAdapter.init();
		mAdapter.initAdd();
	});
</script>
