<!-- BEGIN PAGE CONTAINER-->
<!-- BEGIN PAGE HEADER-->
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="/">SWANSOFT Home</a>
				<span class="icon-angle-right"></span>
			</li>
			<li>
				<a href="javascript:;"><%= className %></a>
				<span class="icon-angle-right"></span>
			</li>
			<li><a href="javascript:;"><%= subClassName %></a></li>
		</ul>
	</div>
</div>
<!-- END PAGE HEADER-->
<div class="container-fluid">
	<!-- BEGIN PAGE CONTENT-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet box blue tabbable">
				<div class="portlet-title">
					<div class="caption">
						<i class="icon-reorder"></i>
						<span class="hidden-480"><%= subClassName %></span>
					</div>
				</div>
				<div class="portlet-body form">
					<div class="tabbable portlet-tabs">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#portlet_tab1" data-toggle="tab">Default</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="portlet_tab1">
								<!-- BEGIN FORM-->
								<form action="/madapter_doAdd" method="post" class="form-horizontal" id="monitorForm">
									<div class="control-group">
										<label class="control-label">监管器名称<span class="required">*</span></label>
										<div class="controls">
											<input type="text" name="name" placeholder="monitor name" class="m-wrap medium" />
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">STEPS<span class="required">*</span></label>
										<div class="controls">
											<input type="text" placeholder="300" name="steps" class="m-wrap medium" />
										</div>
									</div>
									<div class="control-group">
										<label class="control-label">监管器描述</label>
										<div class="controls">
											<textarea class="large m-wrap" name="display_name" rows="3"></textarea>
										</div>
									</div>
									<div class="form-actions">
										<button type="button" class="btn blue" id="monitorBtn"><i class="icon-ok"></i> Save</button>
										<button type="button" class="btn">Cancel</button>
									</div>
								</form>
								<!-- END FORM-->
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- END SAMPLE FORM PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT-->
</div>
<!-- END PAGE CONTAINER-->

<script src="media/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="js/madapter.js" type="text/javascript"></script>
<script type="text/javascript">
	var SwanmAdapter = new SwanmAdapter();
	SwanmAdapter.setThisName('swanMonitor');
	SwanmAdapter.init();
</script>
