<link href="media/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<!-- BEGIN PAGE CONTAINER-->
<!-- BEGIN PAGE HEADER-->
<div class="row-fluid">
	<div class="span12">
		<ul class="breadcrumb">
			<li>
				<i class="icon-home"></i>
				<a href="/">SWANSOFT Home</a>
				<span class="icon-angle-right"></span>
			</li>
			<li>
				<a href="javascript:;"><%= className %></a>
				<span class="icon-angle-right"></span>
			</li>
			<li><a href="javascript:;"><%= subClassName %></a></li>
		</ul>
	</div>
</div>
<!-- END PAGE HEADER-->
<div class="container-fluid">
	<!-- BEGIN PAGE CONTENT-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption">
						<i class="icon-reorder"></i>
						<span class="hidden-480"><%= subClassName %></span>
					</div>
				</div>
				<div class="portlet-body form">
				<!-- BEGIN FORM-->
					<form action="#" method="post" class="form-horizontal" id="mAdapterAttrForm">
						<!-- todo 最后修改 -->
						<input type="hidden" name="madapter_id" value="1">
						<div class="control-group">
							<label class="control-label">属性名称<span class="required">*</span></label>
							<div class="controls">
								<input type="text" name="name" placeholder="mAdapter Attr Name" class="m-wrap span6" />
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">表单类型<span class="required">*</span></label>
							<div class="controls">
								<label class="radio line">
								<input type="radio" name="form_type" value="1"/>
								input
								</label>
								<label class="radio line">
								<input type="radio" name="form_type" value="2"/>
								select
								</label>
								<label class="radio line">
								<input type="radio" name="form_type" value="3"/>
								checkbox
								</label>
								<label class="radio line">
								<input type="radio" name="form_type" value="4"/>
								textarea
								</label>
								<div id="madapter_type_error"></div>	
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">表单数据</label>
							<div class="controls">
								<input class="span6 m-wrap" type="text" name="form_data" placeholder="select/checked表单类型有效" disabled />
								<span class="help-inline">Some hint here</span>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">属性描述</label>
							<div class="controls">
								<textarea class="span6 m-wrap" name="display_name" rows="3"></textarea>
							</div>
						</div>
						<div class="form-actions">
							<button type="button" class="btn blue" id="mAdapter_btn"><i class="icon-ok"></i> Save</button>
							<button type="button" class="btn">Cancel</button>
						</div>
					</form>
					<!-- END FORM-->
				</div>
			</div>
			<!-- END SAMPLE FORM PORTLET-->
		</div>
	</div>
	<!-- END PAGE CONTENT-->
</div>
<!-- END PAGE CONTAINER-->

<script src="media/js/jquery.uniform.min.js" type="text/javascript"></script>
<script src="media/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="js/mAdapterAttr.js" type="text/javascript"></script>

<script type="text/javascript">
	jQuery(document).ready(function() {
		var mAdapterAttr = new SwanmAdapterAttr();

		mAdapterAttr.handleUniform();
		mAdapterAttr.init();
		mAdapterAttr.initAdd();
	});
</script>
